apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-dyn-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-00c1327fb28d4d3a9
  directoryPerms: "700"
  basepath: "/prod"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "efs-dyn-sc"
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    purpose: efs-vol-practice
spec:
  containers:
    - name: nginx-cont
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: efs-vol
  volumes:
    - name: efs-vol
      persistentVolumeClaim:
        claimName: efs-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: efs-lb-svc
spec:
  type: LoadBalancer
  selector:
    purpose: efs-vol-practice
  ports:
    - port: 80
      targetPort: 80
