---
apiVersion: v1 
kind: Service
metadata:
  name: headless-svc-sts
  labels:
    svc: headless-svc-sts-label
spec:
  ports:
    - port: 80
      name: web 
  clusterIP: None
  selector:
    app: ngnix-sts-app
