---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    server: redis-cache-server
    env: prod
spec:
  containers:
    - name: redis-cont
      image: redis:latest
      ports:
        - containerPort: 6379
        
