---
apiVersion: v1
kind: Pod
metadata:
  name: result-pod
  labels:
    result: result-check
    env: prod
spec:
  containers:
    - name: result-cont
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80
