---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-fn-lb
spec:
  selector:
    app: fn-voting-app
    env: prod
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
