---
apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    app: fn-voting-app
    env: prod
spec:
  containers:
    - name: voting-app-cont
      image: dockersamples/examplevotingapp_vote
