apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::805973703993:role/eksctl-k8s-users-nodegroup-ng-7df9-NodeInstanceRole-GsBai36k4rgQ
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::805973703993:user/sandeep
      username: sandeep
      groups:
        - system:authenticated

    - userarn: arn:aws:iam::805973703993:user/vijay
      username: vijay
      groups:
        - system:authenticated
kind: ConfigMap
metadata:
  creationTimestamp: "2025-12-23T16:09:41Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1173"
  uid: 2e9a5c39-854e-4c44-888e-94bed6f4ed3a
