---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc 
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: dyn-ebs-pvc
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    web: nginx-web
spec:
  containers:
    - name: nginx-cont
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: dyn-ebs-vol 
  volumes:
    - name: dyn-ebs-vol
      persistentVolumeClaim:
        claimName: dyn-ebs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-svc
spec:
  selector:
    web: nginx-web
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
