---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-024404b0e73db6792
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-pvc
spec:
  storageClassName: ""
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-static-pod
  labels:
    purpose: ebs-static-prov
spec:
  containers:
    - name: ebs-static-prov-cont
      image: sandeepakula01/mydocker_repo:insta_page
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /var/www/html
          name: ebs-static
  volumes:
    - name: ebs-static
      persistentVolumeClaim:
        claimName: ebs-static-pvc
  nodeSelector:
    topology.kubernetes.io/zone: ap-south-1b
---
apiVersion: v1 
kind: Service
metadata:
  name: ebs-static-lb-svc
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-static-prov
  ports:
    - port: 80
      targetPort: 80
