---
apiVersion: v1  
kind: Pod
metadata:
  name: pod-using-prefered-3
  labels:
    app: backend-app
spec:
  containers:
    - name: nginx-pod
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: env
                operator: In 
                values:
                  - prod
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In 
                values:
                  - ap-south-1b
          weight: 10
