---
apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec-pod
spec:
  containers:
    - name: nginx-cont
      image: nginx
      ports:
        - containerPort: 80
      livenessProbe:
        exec:
          command:
            - cat
            - /usr/share/nginx/html/iindex.html
        initialDelaySeconds: 5
        periodSeconds: 10
        failureThreshold: 2
