---
apiVersion: v1
kind: Pod
metadata:
  name: liveness-http-pod
spec:
  containers:
    - name: nginx-cont
      image: nginx
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
        failureThreshold: 3
