---
apiVersion: v1
kind: Pod
metadata:
  name: readiness-http-pod
spec:
  containers:
    - name: nginx-cont
      image: nginx
      ports:
        - containerPort: 80
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 10
        failureThreshold: 2
