
---
apiVersion: v1
kind: Pod
metadata:
  name: liveness-http-pod
spec:
  containers:
    - name: nginx-cont
      image: nginx
      ports:
        - containerPort: 80
      startupProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10  # Gives grace time to appn to initialize 
        periodSeconds: 10
        failureThreshold: 30 #here waits upto 5mins to start the appn (10 * 30 == 300 sec)
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 10
        failureThreshold: 2
