apiVersion: v1
kind: Pod
metadata:
  name: sa-test-pod
  namespace: dev
spec:
  serviceAccountName: dev-sa
  containers:
    - name: kubectl-test
      image: bitnami/kubectl:latest
      command:
        - sleep
        - "3600"
